# Generated by Django 4.1.7 on 2023-02-19 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('duration', models.CharField(default=None, max_length=10, null=True)),
                ('rating', models.CharField(choices=[('PG', 'A'), ('PG-13', 'B'), ('R', 'C'), ('NC-17', 'D'), ('G', 'Default')], default='G', max_length=20)),
                ('synopsis', models.TextField(default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
