# Generated by Django 4.1.7 on 2023-02-20 03:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_movieorder_movie_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='orders',
            field=models.ManyToManyField(related_name='movie_orders', through='movies.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
