# Generated by Django 4.1.7 on 2023-02-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='owner',
            new_name='user',
        ),
    ]
